/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * shadow-app
 * OpenAPI spec version: 1.0.0
 */
export interface ErrorFieldDto {
  field: string;
  msg: string;
}

export interface ErrorResponseDto {
  code: string;
  type: string;
  message: string;
  fields?: ErrorFieldDto[];
}

export interface CreateSenderProfileBody {
  key: string;
  displayName?: string;
  isActive?: boolean;
}

export interface SenderProfileResponse {
  key: string;
  displayName?: string;
  id: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ListSenderProfileResponse {
  total: number;
  limit: number;
  offset: number;
  items: SenderProfileResponse[];
}

export interface UpdateSenderProfileBody {
  displayName?: string;
  isActive?: boolean;
}

export type CreateSenderEndpointBodyChannel = (typeof CreateSenderEndpointBodyChannel)[keyof typeof CreateSenderEndpointBodyChannel];

export const CreateSenderEndpointBodyChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const;

export type CreateSenderEndpointBodyProvider = (typeof CreateSenderEndpointBodyProvider)[keyof typeof CreateSenderEndpointBodyProvider];

export const CreateSenderEndpointBodyProvider = {
  DEV: 'DEV',
  SENDGRID: 'SENDGRID',
  TWILIO: 'TWILIO',
  FIREBASE: 'FIREBASE',
  AWS_SES: 'AWS_SES',
} as const;

export interface CreateSenderEndpointBody {
  channel: CreateSenderEndpointBodyChannel;
  provider: CreateSenderEndpointBodyProvider;
  identifier: string;
  weight?: number;
  isActive?: boolean;
}

export type SenderEndpointResponseChannel = (typeof SenderEndpointResponseChannel)[keyof typeof SenderEndpointResponseChannel];

export const SenderEndpointResponseChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const;

export type SenderEndpointResponseProvider = (typeof SenderEndpointResponseProvider)[keyof typeof SenderEndpointResponseProvider];

export const SenderEndpointResponseProvider = {
  DEV: 'DEV',
  SENDGRID: 'SENDGRID',
  TWILIO: 'TWILIO',
  FIREBASE: 'FIREBASE',
  AWS_SES: 'AWS_SES',
} as const;

export interface SenderEndpointResponse {
  channel: SenderEndpointResponseChannel;
  provider: SenderEndpointResponseProvider;
  identifier: string;
  id: string;
  senderProfileId: string;
  weight: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ListSenderEndpointResponse {
  total: number;
  limit: number;
  offset: number;
  items: SenderEndpointResponse[];
}

export interface UpdateSenderEndpointBody {
  identifier?: string;
  weight?: number;
  isActive?: boolean;
}

export type CreateRoutingRuleBodyMessageType = (typeof CreateRoutingRuleBodyMessageType)[keyof typeof CreateRoutingRuleBodyMessageType];

export const CreateRoutingRuleBodyMessageType = {
  OTP: 'OTP',
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
} as const;

export interface CreateRoutingRuleBody {
  /** @pattern ^[0-9]+$ */
  senderProfileId: string;
  messageType?: CreateRoutingRuleBodyMessageType;
  region?: string;
  service?: string;
}

export type SenderRoutingRuleResponseMessageType = (typeof SenderRoutingRuleResponseMessageType)[keyof typeof SenderRoutingRuleResponseMessageType];

export const SenderRoutingRuleResponseMessageType = {
  OTP: 'OTP',
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
} as const;

export interface SenderRoutingRuleResponse {
  /** @pattern ^[0-9]+$ */
  senderProfileId: string;
  messageType?: SenderRoutingRuleResponseMessageType;
  region?: string;
  service?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ListSenderRoutingRuleResponse {
  total: number;
  limit: number;
  offset: number;
  items: SenderRoutingRuleResponse[];
}

export type SenderRoutingRuleDetailResponseMessageType = (typeof SenderRoutingRuleDetailResponseMessageType)[keyof typeof SenderRoutingRuleDetailResponseMessageType];

export const SenderRoutingRuleDetailResponseMessageType = {
  OTP: 'OTP',
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
} as const;

export interface SenderRoutingRuleDetailResponse {
  /** @pattern ^[0-9]+$ */
  senderProfileId: string;
  messageType?: SenderRoutingRuleDetailResponseMessageType;
  region?: string;
  service?: string;
  createdAt: string;
  updatedAt: string;
  profile: SenderProfileResponse;
}

export interface UpdateSenderRoutingRuleBody {
  /** @pattern ^[0-9]+$ */
  senderProfileId: string;
}

export interface NotificationDeliveryStats {
  total: number;
  succeeded: number;
  failed: number;
  pending: number;
}

export interface NotificationChannelStats {
  email: NotificationDeliveryStats;
  sms: NotificationDeliveryStats;
  push: NotificationDeliveryStats;
}

export interface NotificationStats {
  date: string;
  overall: NotificationDeliveryStats;
  channels: NotificationChannelStats;
}

export interface NotificationStatsWithDate {
  total: number;
  succeeded: number;
  failed: number;
  pending: number;
  date: string;
}

export interface NotificationStatsTrend {
  fromDate: string;
  toDate: string;
  stats: NotificationStatsWithDate[];
}

export interface DashboardStats {
  today: NotificationStats;
  trend: NotificationStatsTrend;
}

export type CreateTemplateGroupBodyMessageType = (typeof CreateTemplateGroupBodyMessageType)[keyof typeof CreateTemplateGroupBodyMessageType];

export const CreateTemplateGroupBodyMessageType = {
  OTP: 'OTP',
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
} as const;

export type CreateTemplateGroupBodyPriority = (typeof CreateTemplateGroupBodyPriority)[keyof typeof CreateTemplateGroupBodyPriority];

export const CreateTemplateGroupBodyPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const;

export interface CreateTemplateGroupBody {
  templateKey: string;
  messageType: CreateTemplateGroupBodyMessageType;
  description?: string;
  priority?: CreateTemplateGroupBodyPriority;
  isActive?: boolean;
}

export type TemplateGroupResponseMessageType = (typeof TemplateGroupResponseMessageType)[keyof typeof TemplateGroupResponseMessageType];

export const TemplateGroupResponseMessageType = {
  OTP: 'OTP',
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
} as const;

export type TemplateGroupResponsePriority = (typeof TemplateGroupResponsePriority)[keyof typeof TemplateGroupResponsePriority];

export const TemplateGroupResponsePriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const;

export interface TemplateGroupResponse {
  templateKey: string;
  messageType: TemplateGroupResponseMessageType;
  description?: string;
  priority?: TemplateGroupResponsePriority;
  isActive?: boolean;
  id: string;
  createdAt: string;
  updatedAt: string;
}

export interface ListTemplateGroupResponse {
  total: number;
  limit: number;
  offset: number;
  items: TemplateGroupResponse[];
}

export type UpdateTemplateGroupBodyMessageType = (typeof UpdateTemplateGroupBodyMessageType)[keyof typeof UpdateTemplateGroupBodyMessageType];

export const UpdateTemplateGroupBodyMessageType = {
  OTP: 'OTP',
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
} as const;

export type UpdateTemplateGroupBodyPriority = (typeof UpdateTemplateGroupBodyPriority)[keyof typeof UpdateTemplateGroupBodyPriority];

export const UpdateTemplateGroupBodyPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
} as const;

export interface UpdateTemplateGroupBody {
  messageType?: UpdateTemplateGroupBodyMessageType;
  description?: string;
  priority?: UpdateTemplateGroupBodyPriority;
  isActive?: boolean;
}

export type TemplateVariantResponseChannel = (typeof TemplateVariantResponseChannel)[keyof typeof TemplateVariantResponseChannel];

export const TemplateVariantResponseChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const;

export interface TemplateVariantResponse {
  channel: TemplateVariantResponseChannel;
  locale: string;
  subject?: string;
  body: string;
  isActive: boolean;
  id: string;
  createdAt: string;
  updatedAt: string;
}

export interface ListTemplateVariantResponse {
  total: number;
  limit: number;
  offset: number;
  items: TemplateVariantResponse[];
}

export type CreateTemplateVariantBodyChannel = (typeof CreateTemplateVariantBodyChannel)[keyof typeof CreateTemplateVariantBodyChannel];

export const CreateTemplateVariantBodyChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const;

export interface CreateTemplateVariantBody {
  channel: CreateTemplateVariantBodyChannel;
  locale: string;
  subject?: string;
  body: string;
  isActive: boolean;
}

export interface UpdateTemplateVariantBody {
  subject?: string;
  body?: string;
  isActive?: boolean;
}

export type CreateNotificationBodyPayload = { [key: string]: unknown };

export interface NotificationRecipients {
  email?: string;
  phone?: string;
  push?: string;
}

export interface CreateNotificationBody {
  templateKey: string;
  recipients: NotificationRecipients;
  payload?: CreateNotificationBodyPayload;
  locale?: string;
  service?: string;
}

export type CreateNotificationResponseStatus = (typeof CreateNotificationResponseStatus)[keyof typeof CreateNotificationResponseStatus];

export const CreateNotificationResponseStatus = {
  ACCEPTED: 'ACCEPTED',
  PARTIAL_ACCEPTED: 'PARTIAL_ACCEPTED',
  FAILED: 'FAILED',
} as const;

export type NotificationChannelResponseChannel = (typeof NotificationChannelResponseChannel)[keyof typeof NotificationChannelResponseChannel];

export const NotificationChannelResponseChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const;

export type NotificationChannelResponseStatus = (typeof NotificationChannelResponseStatus)[keyof typeof NotificationChannelResponseStatus];

export const NotificationChannelResponseStatus = {
  QUEUED: 'QUEUED',
  FAILED: 'FAILED',
} as const;

export interface NotificationChannelResponse {
  channel: NotificationChannelResponseChannel;
  status: NotificationChannelResponseStatus;
  locale?: string;
  jobId?: string;
  error?: ErrorResponseDto;
}

export interface CreateNotificationResponse {
  status: CreateNotificationResponseStatus;
  channelResults: NotificationChannelResponse[];
}

export type ListSenderProfilesParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset: number;
  sortOrder?: ListSenderProfilesSortOrder;
  sortBy?: ListSenderProfilesSortBy;
  key?: string;
  isActive?: boolean;
};

export type ListSenderProfilesSortOrder = (typeof ListSenderProfilesSortOrder)[keyof typeof ListSenderProfilesSortOrder];

export const ListSenderProfilesSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ListSenderProfilesSortBy = (typeof ListSenderProfilesSortBy)[keyof typeof ListSenderProfilesSortBy];

export const ListSenderProfilesSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ListSenderEndpointsParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset: number;
  sortOrder?: ListSenderEndpointsSortOrder;
  sortBy?: ListSenderEndpointsSortBy;
  channel?: ListSenderEndpointsChannel;
  provider?: ListSenderEndpointsProvider;
  isActive?: boolean;
};

export type ListSenderEndpointsSortOrder = (typeof ListSenderEndpointsSortOrder)[keyof typeof ListSenderEndpointsSortOrder];

export const ListSenderEndpointsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ListSenderEndpointsSortBy = (typeof ListSenderEndpointsSortBy)[keyof typeof ListSenderEndpointsSortBy];

export const ListSenderEndpointsSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ListSenderEndpointsChannel = (typeof ListSenderEndpointsChannel)[keyof typeof ListSenderEndpointsChannel];

export const ListSenderEndpointsChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const;

export type ListSenderEndpointsProvider = (typeof ListSenderEndpointsProvider)[keyof typeof ListSenderEndpointsProvider];

export const ListSenderEndpointsProvider = {
  DEV: 'DEV',
  SENDGRID: 'SENDGRID',
  TWILIO: 'TWILIO',
  FIREBASE: 'FIREBASE',
  AWS_SES: 'AWS_SES',
} as const;

export type ListSenderRoutingRulesParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset: number;
  sortOrder?: ListSenderRoutingRulesSortOrder;
  sortBy?: ListSenderRoutingRulesSortBy;
  messageType?: ListSenderRoutingRulesMessageType;
  region?: string;
  serviceName?: string;
};

export type ListSenderRoutingRulesSortOrder = (typeof ListSenderRoutingRulesSortOrder)[keyof typeof ListSenderRoutingRulesSortOrder];

export const ListSenderRoutingRulesSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ListSenderRoutingRulesSortBy = (typeof ListSenderRoutingRulesSortBy)[keyof typeof ListSenderRoutingRulesSortBy];

export const ListSenderRoutingRulesSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ListSenderRoutingRulesMessageType = (typeof ListSenderRoutingRulesMessageType)[keyof typeof ListSenderRoutingRulesMessageType];

export const ListSenderRoutingRulesMessageType = {
  OTP: 'OTP',
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
} as const;

export type ListTemplateGroupsParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset: number;
  sortOrder?: ListTemplateGroupsSortOrder;
  sortBy?: ListTemplateGroupsSortBy;
  key?: string;
};

export type ListTemplateGroupsSortOrder = (typeof ListTemplateGroupsSortOrder)[keyof typeof ListTemplateGroupsSortOrder];

export const ListTemplateGroupsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ListTemplateGroupsSortBy = (typeof ListTemplateGroupsSortBy)[keyof typeof ListTemplateGroupsSortBy];

export const ListTemplateGroupsSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ListTemplateVariantsParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset: number;
  sortOrder?: ListTemplateVariantsSortOrder;
  sortBy?: ListTemplateVariantsSortBy;
  channel?: ListTemplateVariantsChannel;
  locale?: string;
};

export type ListTemplateVariantsSortOrder = (typeof ListTemplateVariantsSortOrder)[keyof typeof ListTemplateVariantsSortOrder];

export const ListTemplateVariantsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ListTemplateVariantsSortBy = (typeof ListTemplateVariantsSortBy)[keyof typeof ListTemplateVariantsSortBy];

export const ListTemplateVariantsSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type ListTemplateVariantsChannel = (typeof ListTemplateVariantsChannel)[keyof typeof ListTemplateVariantsChannel];

export const ListTemplateVariantsChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
} as const;

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * @summary Get Health
 */
export type getHealthResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type getHealthResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};
export type getHealthResponseError = (getHealthResponse4xx | getHealthResponse5xx) & {
  headers: Headers;
};

export type getHealthResponse = getHealthResponseError;

export const getGetHealthUrl = () => {
  return `/api/v1/health`;
};

export const getHealth = async (options?: RequestInit): Promise<getHealthResponse> => {
  const res = await fetch(getGetHealthUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getHealthResponse;
};

/**
 * @summary Create Sender Profile
 */
export type createSenderProfileResponse201 = {
  data: SenderProfileResponse;
  status: 201;
};

export type createSenderProfileResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type createSenderProfileResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type createSenderProfileResponseSuccess = createSenderProfileResponse201 & {
  headers: Headers;
};
export type createSenderProfileResponseError = (createSenderProfileResponse4xx | createSenderProfileResponse5xx) & {
  headers: Headers;
};

export type createSenderProfileResponse = createSenderProfileResponseSuccess | createSenderProfileResponseError;

export const getCreateSenderProfileUrl = () => {
  return `/api/v1/sender-profiles`;
};

export const createSenderProfile = async (createSenderProfileBody: CreateSenderProfileBody, options?: RequestInit): Promise<createSenderProfileResponse> => {
  const res = await fetch(getCreateSenderProfileUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSenderProfileBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSenderProfileResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createSenderProfileResponse;
};

/**
 * @summary List Sender Profiles
 */
export type listSenderProfilesResponse200 = {
  data: ListSenderProfileResponse;
  status: 200;
};

export type listSenderProfilesResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type listSenderProfilesResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type listSenderProfilesResponseSuccess = listSenderProfilesResponse200 & {
  headers: Headers;
};
export type listSenderProfilesResponseError = (listSenderProfilesResponse4xx | listSenderProfilesResponse5xx) & {
  headers: Headers;
};

export type listSenderProfilesResponse = listSenderProfilesResponseSuccess | listSenderProfilesResponseError;

export const getListSenderProfilesUrl = (params: ListSenderProfilesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sender-profiles?${stringifiedParams}` : `/api/v1/sender-profiles`;
};

export const listSenderProfiles = async (params: ListSenderProfilesParams, options?: RequestInit): Promise<listSenderProfilesResponse> => {
  const res = await fetch(getListSenderProfilesUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSenderProfilesResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listSenderProfilesResponse;
};

/**
 * @summary Get Sender Profile
 */
export type getSenderProfileResponse200 = {
  data: SenderProfileResponse;
  status: 200;
};

export type getSenderProfileResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type getSenderProfileResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type getSenderProfileResponseSuccess = getSenderProfileResponse200 & {
  headers: Headers;
};
export type getSenderProfileResponseError = (getSenderProfileResponse4xx | getSenderProfileResponse5xx) & {
  headers: Headers;
};

export type getSenderProfileResponse = getSenderProfileResponseSuccess | getSenderProfileResponseError;

export const getGetSenderProfileUrl = (profileId: string) => {
  return `/api/v1/sender-profiles/${profileId}`;
};

export const getSenderProfile = async (profileId: string, options?: RequestInit): Promise<getSenderProfileResponse> => {
  const res = await fetch(getGetSenderProfileUrl(profileId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSenderProfileResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getSenderProfileResponse;
};

/**
 * @summary Update Sender Profile
 */
export type updateSenderProfileResponse200 = {
  data: SenderProfileResponse;
  status: 200;
};

export type updateSenderProfileResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type updateSenderProfileResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type updateSenderProfileResponseSuccess = updateSenderProfileResponse200 & {
  headers: Headers;
};
export type updateSenderProfileResponseError = (updateSenderProfileResponse4xx | updateSenderProfileResponse5xx) & {
  headers: Headers;
};

export type updateSenderProfileResponse = updateSenderProfileResponseSuccess | updateSenderProfileResponseError;

export const getUpdateSenderProfileUrl = (profileId: string) => {
  return `/api/v1/sender-profiles/${profileId}`;
};

export const updateSenderProfile = async (profileId: string, updateSenderProfileBody: UpdateSenderProfileBody, options?: RequestInit): Promise<updateSenderProfileResponse> => {
  const res = await fetch(getUpdateSenderProfileUrl(profileId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSenderProfileBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateSenderProfileResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as updateSenderProfileResponse;
};

/**
 * @summary Delete Sender Profile
 */
export type deleteSenderProfileResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type deleteSenderProfileResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};
export type deleteSenderProfileResponseError = (deleteSenderProfileResponse4xx | deleteSenderProfileResponse5xx) & {
  headers: Headers;
};

export type deleteSenderProfileResponse = deleteSenderProfileResponseError;

export const getDeleteSenderProfileUrl = (profileId: string) => {
  return `/api/v1/sender-profiles/${profileId}`;
};

export const deleteSenderProfile = async (profileId: string, options?: RequestInit): Promise<deleteSenderProfileResponse> => {
  const res = await fetch(getDeleteSenderProfileUrl(profileId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteSenderProfileResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as deleteSenderProfileResponse;
};

/**
 * @summary Create Sender Endpoint
 */
export type createSenderEndpointResponse201 = {
  data: SenderEndpointResponse;
  status: 201;
};

export type createSenderEndpointResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type createSenderEndpointResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type createSenderEndpointResponseSuccess = createSenderEndpointResponse201 & {
  headers: Headers;
};
export type createSenderEndpointResponseError = (createSenderEndpointResponse4xx | createSenderEndpointResponse5xx) & {
  headers: Headers;
};

export type createSenderEndpointResponse = createSenderEndpointResponseSuccess | createSenderEndpointResponseError;

export const getCreateSenderEndpointUrl = (profileId: string) => {
  return `/api/v1/sender-profiles/${profileId}/endpoints`;
};

export const createSenderEndpoint = async (profileId: string, createSenderEndpointBody: CreateSenderEndpointBody, options?: RequestInit): Promise<createSenderEndpointResponse> => {
  const res = await fetch(getCreateSenderEndpointUrl(profileId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSenderEndpointBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSenderEndpointResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createSenderEndpointResponse;
};

/**
 * @summary List Sender Endpoints
 */
export type listSenderEndpointsResponse200 = {
  data: ListSenderEndpointResponse;
  status: 200;
};

export type listSenderEndpointsResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type listSenderEndpointsResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type listSenderEndpointsResponseSuccess = listSenderEndpointsResponse200 & {
  headers: Headers;
};
export type listSenderEndpointsResponseError = (listSenderEndpointsResponse4xx | listSenderEndpointsResponse5xx) & {
  headers: Headers;
};

export type listSenderEndpointsResponse = listSenderEndpointsResponseSuccess | listSenderEndpointsResponseError;

export const getListSenderEndpointsUrl = (profileId: string, params: ListSenderEndpointsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sender-profiles/${profileId}/endpoints?${stringifiedParams}` : `/api/v1/sender-profiles/${profileId}/endpoints`;
};

export const listSenderEndpoints = async (profileId: string, params: ListSenderEndpointsParams, options?: RequestInit): Promise<listSenderEndpointsResponse> => {
  const res = await fetch(getListSenderEndpointsUrl(profileId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSenderEndpointsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listSenderEndpointsResponse;
};

/**
 * @summary Get Sender Endpoint
 */
export type getSenderEndpointResponse200 = {
  data: SenderEndpointResponse;
  status: 200;
};

export type getSenderEndpointResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type getSenderEndpointResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type getSenderEndpointResponseSuccess = getSenderEndpointResponse200 & {
  headers: Headers;
};
export type getSenderEndpointResponseError = (getSenderEndpointResponse4xx | getSenderEndpointResponse5xx) & {
  headers: Headers;
};

export type getSenderEndpointResponse = getSenderEndpointResponseSuccess | getSenderEndpointResponseError;

export const getGetSenderEndpointUrl = (profileId: string, endpointId: string) => {
  return `/api/v1/sender-profiles/${profileId}/endpoints/${endpointId}`;
};

export const getSenderEndpoint = async (profileId: string, endpointId: string, options?: RequestInit): Promise<getSenderEndpointResponse> => {
  const res = await fetch(getGetSenderEndpointUrl(profileId, endpointId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSenderEndpointResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getSenderEndpointResponse;
};

/**
 * @summary Update Sender Endpoint
 */
export type updateSenderEndpointResponse200 = {
  data: SenderEndpointResponse;
  status: 200;
};

export type updateSenderEndpointResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type updateSenderEndpointResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type updateSenderEndpointResponseSuccess = updateSenderEndpointResponse200 & {
  headers: Headers;
};
export type updateSenderEndpointResponseError = (updateSenderEndpointResponse4xx | updateSenderEndpointResponse5xx) & {
  headers: Headers;
};

export type updateSenderEndpointResponse = updateSenderEndpointResponseSuccess | updateSenderEndpointResponseError;

export const getUpdateSenderEndpointUrl = (profileId: string, endpointId: string) => {
  return `/api/v1/sender-profiles/${profileId}/endpoints/${endpointId}`;
};

export const updateSenderEndpoint = async (
  profileId: string,
  endpointId: string,
  updateSenderEndpointBody: UpdateSenderEndpointBody,
  options?: RequestInit,
): Promise<updateSenderEndpointResponse> => {
  const res = await fetch(getUpdateSenderEndpointUrl(profileId, endpointId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSenderEndpointBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateSenderEndpointResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as updateSenderEndpointResponse;
};

/**
 * @summary Delete Sender Endpoint
 */
export type deleteSenderEndpointResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type deleteSenderEndpointResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};
export type deleteSenderEndpointResponseError = (deleteSenderEndpointResponse4xx | deleteSenderEndpointResponse5xx) & {
  headers: Headers;
};

export type deleteSenderEndpointResponse = deleteSenderEndpointResponseError;

export const getDeleteSenderEndpointUrl = (profileId: string, endpointId: string) => {
  return `/api/v1/sender-profiles/${profileId}/endpoints/${endpointId}`;
};

export const deleteSenderEndpoint = async (profileId: string, endpointId: string, options?: RequestInit): Promise<deleteSenderEndpointResponse> => {
  const res = await fetch(getDeleteSenderEndpointUrl(profileId, endpointId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteSenderEndpointResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as deleteSenderEndpointResponse;
};

/**
 * @summary Create Sender Routing Rule
 */
export type createSenderRoutingRuleResponse201 = {
  data: SenderRoutingRuleResponse;
  status: 201;
};

export type createSenderRoutingRuleResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type createSenderRoutingRuleResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type createSenderRoutingRuleResponseSuccess = createSenderRoutingRuleResponse201 & {
  headers: Headers;
};
export type createSenderRoutingRuleResponseError = (createSenderRoutingRuleResponse4xx | createSenderRoutingRuleResponse5xx) & {
  headers: Headers;
};

export type createSenderRoutingRuleResponse = createSenderRoutingRuleResponseSuccess | createSenderRoutingRuleResponseError;

export const getCreateSenderRoutingRuleUrl = () => {
  return `/api/v1/sender-routing-rules`;
};

export const createSenderRoutingRule = async (createRoutingRuleBody: CreateRoutingRuleBody, options?: RequestInit): Promise<createSenderRoutingRuleResponse> => {
  const res = await fetch(getCreateSenderRoutingRuleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRoutingRuleBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSenderRoutingRuleResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createSenderRoutingRuleResponse;
};

/**
 * @summary List Sender Routing Rules
 */
export type listSenderRoutingRulesResponse200 = {
  data: ListSenderRoutingRuleResponse;
  status: 200;
};

export type listSenderRoutingRulesResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type listSenderRoutingRulesResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type listSenderRoutingRulesResponseSuccess = listSenderRoutingRulesResponse200 & {
  headers: Headers;
};
export type listSenderRoutingRulesResponseError = (listSenderRoutingRulesResponse4xx | listSenderRoutingRulesResponse5xx) & {
  headers: Headers;
};

export type listSenderRoutingRulesResponse = listSenderRoutingRulesResponseSuccess | listSenderRoutingRulesResponseError;

export const getListSenderRoutingRulesUrl = (params: ListSenderRoutingRulesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sender-routing-rules?${stringifiedParams}` : `/api/v1/sender-routing-rules`;
};

export const listSenderRoutingRules = async (params: ListSenderRoutingRulesParams, options?: RequestInit): Promise<listSenderRoutingRulesResponse> => {
  const res = await fetch(getListSenderRoutingRulesUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSenderRoutingRulesResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listSenderRoutingRulesResponse;
};

/**
 * @summary Get Sender Routing Rule
 */
export type getSenderRoutingRuleResponse200 = {
  data: SenderRoutingRuleDetailResponse;
  status: 200;
};

export type getSenderRoutingRuleResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type getSenderRoutingRuleResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type getSenderRoutingRuleResponseSuccess = getSenderRoutingRuleResponse200 & {
  headers: Headers;
};
export type getSenderRoutingRuleResponseError = (getSenderRoutingRuleResponse4xx | getSenderRoutingRuleResponse5xx) & {
  headers: Headers;
};

export type getSenderRoutingRuleResponse = getSenderRoutingRuleResponseSuccess | getSenderRoutingRuleResponseError;

export const getGetSenderRoutingRuleUrl = (routingRuleId: string) => {
  return `/api/v1/sender-routing-rules/${routingRuleId}`;
};

export const getSenderRoutingRule = async (routingRuleId: string, options?: RequestInit): Promise<getSenderRoutingRuleResponse> => {
  const res = await fetch(getGetSenderRoutingRuleUrl(routingRuleId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSenderRoutingRuleResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getSenderRoutingRuleResponse;
};

/**
 * @summary Update Sender Routing Rule
 */
export type updateSenderRoutingRuleResponse200 = {
  data: SenderRoutingRuleResponse;
  status: 200;
};

export type updateSenderRoutingRuleResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type updateSenderRoutingRuleResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type updateSenderRoutingRuleResponseSuccess = updateSenderRoutingRuleResponse200 & {
  headers: Headers;
};
export type updateSenderRoutingRuleResponseError = (updateSenderRoutingRuleResponse4xx | updateSenderRoutingRuleResponse5xx) & {
  headers: Headers;
};

export type updateSenderRoutingRuleResponse = updateSenderRoutingRuleResponseSuccess | updateSenderRoutingRuleResponseError;

export const getUpdateSenderRoutingRuleUrl = (routingRuleId: string) => {
  return `/api/v1/sender-routing-rules/${routingRuleId}`;
};

export const updateSenderRoutingRule = async (
  routingRuleId: string,
  updateSenderRoutingRuleBody: UpdateSenderRoutingRuleBody,
  options?: RequestInit,
): Promise<updateSenderRoutingRuleResponse> => {
  const res = await fetch(getUpdateSenderRoutingRuleUrl(routingRuleId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSenderRoutingRuleBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateSenderRoutingRuleResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as updateSenderRoutingRuleResponse;
};

/**
 * @summary Delete Sender Routing Rule
 */
export type deleteSenderRoutingRuleResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type deleteSenderRoutingRuleResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};
export type deleteSenderRoutingRuleResponseError = (deleteSenderRoutingRuleResponse4xx | deleteSenderRoutingRuleResponse5xx) & {
  headers: Headers;
};

export type deleteSenderRoutingRuleResponse = deleteSenderRoutingRuleResponseError;

export const getDeleteSenderRoutingRuleUrl = (routingRuleId: string) => {
  return `/api/v1/sender-routing-rules/${routingRuleId}`;
};

export const deleteSenderRoutingRule = async (routingRuleId: string, options?: RequestInit): Promise<deleteSenderRoutingRuleResponse> => {
  const res = await fetch(getDeleteSenderRoutingRuleUrl(routingRuleId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteSenderRoutingRuleResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as deleteSenderRoutingRuleResponse;
};

/**
 * @summary Get Stats
 */
export type getStatsResponse200 = {
  data: DashboardStats;
  status: 200;
};

export type getStatsResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type getStatsResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse4xx | getStatsResponse5xx) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = () => {
  return `/api/v1/dashboard/stats`;
};

export const getStats = async (options?: RequestInit): Promise<getStatsResponse> => {
  const res = await fetch(getGetStatsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getStatsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getStatsResponse;
};

/**
 * @summary Create Template Group
 */
export type createTemplateGroupResponse201 = {
  data: TemplateGroupResponse;
  status: 201;
};

export type createTemplateGroupResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type createTemplateGroupResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type createTemplateGroupResponseSuccess = createTemplateGroupResponse201 & {
  headers: Headers;
};
export type createTemplateGroupResponseError = (createTemplateGroupResponse4xx | createTemplateGroupResponse5xx) & {
  headers: Headers;
};

export type createTemplateGroupResponse = createTemplateGroupResponseSuccess | createTemplateGroupResponseError;

export const getCreateTemplateGroupUrl = () => {
  return `/api/v1/template-groups`;
};

export const createTemplateGroup = async (createTemplateGroupBody: CreateTemplateGroupBody, options?: RequestInit): Promise<createTemplateGroupResponse> => {
  const res = await fetch(getCreateTemplateGroupUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTemplateGroupBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createTemplateGroupResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createTemplateGroupResponse;
};

/**
 * @summary List Template Groups
 */
export type listTemplateGroupsResponse200 = {
  data: ListTemplateGroupResponse;
  status: 200;
};

export type listTemplateGroupsResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type listTemplateGroupsResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type listTemplateGroupsResponseSuccess = listTemplateGroupsResponse200 & {
  headers: Headers;
};
export type listTemplateGroupsResponseError = (listTemplateGroupsResponse4xx | listTemplateGroupsResponse5xx) & {
  headers: Headers;
};

export type listTemplateGroupsResponse = listTemplateGroupsResponseSuccess | listTemplateGroupsResponseError;

export const getListTemplateGroupsUrl = (params: ListTemplateGroupsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/template-groups?${stringifiedParams}` : `/api/v1/template-groups`;
};

export const listTemplateGroups = async (params: ListTemplateGroupsParams, options?: RequestInit): Promise<listTemplateGroupsResponse> => {
  const res = await fetch(getListTemplateGroupsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listTemplateGroupsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listTemplateGroupsResponse;
};

/**
 * @summary Get Template Group
 */
export type getTemplateGroupResponse200 = {
  data: TemplateGroupResponse;
  status: 200;
};

export type getTemplateGroupResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type getTemplateGroupResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type getTemplateGroupResponseSuccess = getTemplateGroupResponse200 & {
  headers: Headers;
};
export type getTemplateGroupResponseError = (getTemplateGroupResponse4xx | getTemplateGroupResponse5xx) & {
  headers: Headers;
};

export type getTemplateGroupResponse = getTemplateGroupResponseSuccess | getTemplateGroupResponseError;

export const getGetTemplateGroupUrl = (groupId: string) => {
  return `/api/v1/template-groups/${groupId}`;
};

export const getTemplateGroup = async (groupId: string, options?: RequestInit): Promise<getTemplateGroupResponse> => {
  const res = await fetch(getGetTemplateGroupUrl(groupId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTemplateGroupResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getTemplateGroupResponse;
};

/**
 * @summary Update Template Group
 */
export type updateTemplateGroupResponse200 = {
  data: TemplateGroupResponse;
  status: 200;
};

export type updateTemplateGroupResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type updateTemplateGroupResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type updateTemplateGroupResponseSuccess = updateTemplateGroupResponse200 & {
  headers: Headers;
};
export type updateTemplateGroupResponseError = (updateTemplateGroupResponse4xx | updateTemplateGroupResponse5xx) & {
  headers: Headers;
};

export type updateTemplateGroupResponse = updateTemplateGroupResponseSuccess | updateTemplateGroupResponseError;

export const getUpdateTemplateGroupUrl = (groupId: string) => {
  return `/api/v1/template-groups/${groupId}`;
};

export const updateTemplateGroup = async (groupId: string, updateTemplateGroupBody: UpdateTemplateGroupBody, options?: RequestInit): Promise<updateTemplateGroupResponse> => {
  const res = await fetch(getUpdateTemplateGroupUrl(groupId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateTemplateGroupBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTemplateGroupResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as updateTemplateGroupResponse;
};

/**
 * @summary List Template Variants
 */
export type listTemplateVariantsResponse200 = {
  data: ListTemplateVariantResponse;
  status: 200;
};

export type listTemplateVariantsResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type listTemplateVariantsResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type listTemplateVariantsResponseSuccess = listTemplateVariantsResponse200 & {
  headers: Headers;
};
export type listTemplateVariantsResponseError = (listTemplateVariantsResponse4xx | listTemplateVariantsResponse5xx) & {
  headers: Headers;
};

export type listTemplateVariantsResponse = listTemplateVariantsResponseSuccess | listTemplateVariantsResponseError;

export const getListTemplateVariantsUrl = (groupId: string, params: ListTemplateVariantsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/template-groups/${groupId}/variants?${stringifiedParams}` : `/api/v1/template-groups/${groupId}/variants`;
};

export const listTemplateVariants = async (groupId: string, params: ListTemplateVariantsParams, options?: RequestInit): Promise<listTemplateVariantsResponse> => {
  const res = await fetch(getListTemplateVariantsUrl(groupId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listTemplateVariantsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listTemplateVariantsResponse;
};

/**
 * @summary Create Template Variant
 */
export type createTemplateVariantResponse201 = {
  data: TemplateVariantResponse;
  status: 201;
};

export type createTemplateVariantResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type createTemplateVariantResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type createTemplateVariantResponseSuccess = createTemplateVariantResponse201 & {
  headers: Headers;
};
export type createTemplateVariantResponseError = (createTemplateVariantResponse4xx | createTemplateVariantResponse5xx) & {
  headers: Headers;
};

export type createTemplateVariantResponse = createTemplateVariantResponseSuccess | createTemplateVariantResponseError;

export const getCreateTemplateVariantUrl = (groupId: string) => {
  return `/api/v1/template-groups/${groupId}/variants`;
};

export const createTemplateVariant = async (
  groupId: string,
  createTemplateVariantBody: CreateTemplateVariantBody,
  options?: RequestInit,
): Promise<createTemplateVariantResponse> => {
  const res = await fetch(getCreateTemplateVariantUrl(groupId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTemplateVariantBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createTemplateVariantResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createTemplateVariantResponse;
};

/**
 * @summary Get Template Variant
 */
export type getTemplateVariantResponse200 = {
  data: TemplateVariantResponse;
  status: 200;
};

export type getTemplateVariantResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type getTemplateVariantResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type getTemplateVariantResponseSuccess = getTemplateVariantResponse200 & {
  headers: Headers;
};
export type getTemplateVariantResponseError = (getTemplateVariantResponse4xx | getTemplateVariantResponse5xx) & {
  headers: Headers;
};

export type getTemplateVariantResponse = getTemplateVariantResponseSuccess | getTemplateVariantResponseError;

export const getGetTemplateVariantUrl = (groupId: string, variantId: string) => {
  return `/api/v1/template-groups/${groupId}/variants/${variantId}`;
};

export const getTemplateVariant = async (groupId: string, variantId: string, options?: RequestInit): Promise<getTemplateVariantResponse> => {
  const res = await fetch(getGetTemplateVariantUrl(groupId, variantId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTemplateVariantResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getTemplateVariantResponse;
};

/**
 * @summary Update Template Variant
 */
export type updateTemplateVariantResponse200 = {
  data: TemplateVariantResponse;
  status: 200;
};

export type updateTemplateVariantResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type updateTemplateVariantResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type updateTemplateVariantResponseSuccess = updateTemplateVariantResponse200 & {
  headers: Headers;
};
export type updateTemplateVariantResponseError = (updateTemplateVariantResponse4xx | updateTemplateVariantResponse5xx) & {
  headers: Headers;
};

export type updateTemplateVariantResponse = updateTemplateVariantResponseSuccess | updateTemplateVariantResponseError;

export const getUpdateTemplateVariantUrl = (groupId: string, variantId: string) => {
  return `/api/v1/template-groups/${groupId}/variants/${variantId}`;
};

export const updateTemplateVariant = async (
  groupId: string,
  variantId: string,
  updateTemplateVariantBody: UpdateTemplateVariantBody,
  options?: RequestInit,
): Promise<updateTemplateVariantResponse> => {
  const res = await fetch(getUpdateTemplateVariantUrl(groupId, variantId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateTemplateVariantBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTemplateVariantResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as updateTemplateVariantResponse;
};

/**
 * @summary Delete Template Variant
 */
export type deleteTemplateVariantResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type deleteTemplateVariantResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};
export type deleteTemplateVariantResponseError = (deleteTemplateVariantResponse4xx | deleteTemplateVariantResponse5xx) & {
  headers: Headers;
};

export type deleteTemplateVariantResponse = deleteTemplateVariantResponseError;

export const getDeleteTemplateVariantUrl = (groupId: string, variantId: string) => {
  return `/api/v1/template-groups/${groupId}/variants/${variantId}`;
};

export const deleteTemplateVariant = async (groupId: string, variantId: string, options?: RequestInit): Promise<deleteTemplateVariantResponse> => {
  const res = await fetch(getDeleteTemplateVariantUrl(groupId, variantId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteTemplateVariantResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as deleteTemplateVariantResponse;
};

/**
 * @summary Create Notification
 */
export type createNotificationResponse201 = {
  data: CreateNotificationResponse;
  status: 201;
};

export type createNotificationResponse4xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode4xx;
};

export type createNotificationResponse5xx = {
  data: ErrorResponseDto;
  status: HTTPStatusCode5xx;
};

export type createNotificationResponseSuccess = createNotificationResponse201 & {
  headers: Headers;
};
export type createNotificationResponseError = (createNotificationResponse4xx | createNotificationResponse5xx) & {
  headers: Headers;
};

export type createNotificationResponse = createNotificationResponseSuccess | createNotificationResponseError;

export const getCreateNotificationUrl = () => {
  return `/api/v1/notifications`;
};

export const createNotification = async (createNotificationBody: CreateNotificationBody, options?: RequestInit): Promise<createNotificationResponse> => {
  const res = await fetch(getCreateNotificationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createNotificationBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createNotificationResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createNotificationResponse;
};
